---
title: "Sick-leave analysis"
author: "Oddmund Klæboe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    fig_width: 4
    fig_height: 4
    fig_caption: true
    toc: true
    toc_depth: 3
#bibliography: bibliography.bib
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(PxWebApiData))
```

```{r data}


tabell_full<-ApiData("https://data.ssb.no/api/v0/no/table/12441/", 
        Kjonn=list('item', c("0", "1", "2")), 
        NACE2007=list('item', c("00-99", "01-03", "05-09", "10-33", "35-39", "41-43", "45-47", "49-53", "55-56", "58-63", "64-66", "68-75", "77-82", "84", "85", "86-88", "90-99", "00")), 
        Sykefraver2=list('item', c("Alt", "E", "L")), 
        ContentsCode=TRUE, 
        Tid=TRUE)

data_sf_full<- tabell_full[[1]]
# glimpse(data_sf_full)
# names(data_sf_full)
```

```{r rydding}
# Rydder i datasettet
data_sf_full<- data_sf_full %>% 
  rename("næringer" = "næring (SN2007)", 
          "sykefraværstyper" = 'type sykefravær',
       "sykefraværsprosent" = "value") %>% 
  select(-c("statistikkvariabel", "NAstatus"))

#glimpse(data_sf_full)
#names(data_sf_full)
```

\newpage

## **1. Innledning**

Litt om sykefravær

## **2. Gjennomgang av tilgjengelig statistikk**

### **2.1 Alle typer sykefravær, alle næringer, begge kjønn**

```{r oversikt alle, fig.width= 12}

oversikt<-data_sf_full %>% 
  filter(kjønn == "Begge kjønn", 
         næringer == "Alle næringer")

sf_linje_alle<- 
  ggplot(oversikt,aes(x=år,y=sykefraværsprosent, group=sykefraværstyper))+
  geom_line(aes(color= sykefraværstyper), linewidth = 1.0)+
  geom_point() +
  ylim(0, 10)+
  labs(title = "Figur 1: Sykefravær totalt fordelt på fraværstyper", 
       x = "År", y = "Sykefraværsprosent")
sf_linje_alle

```

### **2.2 Kvinner, alle typer sykefravær, alle næringer**

```{r oversikt kvinner, fig.width= 12}

oversikt_kv<-data_sf_full %>% 
  filter(kjønn == "Kvinner", 
         næringer == "Alle næringer")

sf_linje_kvinner<- 
  ggplot(oversikt_kv,aes(x=år,y=sykefraværsprosent, group=sykefraværstyper))+
  geom_line(aes(color= sykefraværstyper), linewidth = 1.0)+
  geom_point() +
  ylim(0, 10)+
  labs(title = "Figur 2: Sykefravær blant kvinner fordelt på fraværstyper", 
       x = "År", y = "Sykefraværsprosent")
sf_linje_kvinner
```

### **2.3 Menn, alle typer sykefravær, alle næringer**

```{r oversikt menn, fig.width= 12}
oversikt_m<-data_sf_full %>% 
  filter(kjønn == "Menn", 
         næringer == "Alle næringer")

sf_linje_menn<- 
  ggplot(oversikt_m,aes(x=år,y=sykefraværsprosent, group=sykefraværstyper))+
  geom_line(aes(color= sykefraværstyper), linewidth = 1.0)+
  geom_point() +
  ylim(0, 10)+
  labs(title = "Figur 3: Sykefravær blant menn fordelt på fraværstyper", 
       x = "År", y = "Sykefraværsprosent")
sf_linje_menn
```

### **2.4 Legemeldt fravær fordelt på kjønn**

```{r legemeldt, fig.width= 12}

oversikt_legemeldt<-data_sf_full %>% 
  filter(næringer == "Alle næringer", sykefraværstyper == "Legemeldt")

#glimpse(oversikt_legemeldt)

sf_linje_legemeldt<- 
  ggplot(oversikt_legemeldt,aes(x=år,y=sykefraværsprosent, group=kjønn))+
  geom_line(aes(color= kjønn), linewidth = 1.0)+
  geom_point() +
  ylim(0, 10)+
  labs(title = "Figur 4: Legemeldt sykefravær fordelt på kjønn", 
       x = "År", y = "Sykefraværsprosent")
sf_linje_legemeldt
```

### **2.5 Legemeldt fravær fordelt på bransjer og kjønn**

```{r legemeldt_bransjer, fig.width= 12}

oversikt_legemeldt<-data_sf_full %>% 
  filter(næringer == "Helse- og sosialtjenester", sykefraværstyper == "Legemeldt")

#glimpse(oversikt_legemeldt)

sf_legemeldt_HS<- 
  ggplot(oversikt_legemeldt,aes(x=år,y=sykefraværsprosent, group=kjønn))+
  geom_line(aes(color= kjønn), linewidth = 1.0)+
  geom_point() +
  ylim(0, 10)+
  labs(title = "Figur 5: Helse- og sosialtjenester \nLegemeldt sykefravær fordelt på kjønn", 
       x = "År", y = "Sykefraværsprosent")
sf_legemeldt_HS
```

```{r}
#bransjeoversikt
bransjer_år<- data_sf_full %>% 
  filter(sykefraværstyper == "Legemeldt") %>%
  pivot_wider(names_from = år, values_from = sykefraværsprosent)
#bransjer_år
```

```{r alle}
#bransjer, alle  - fraværstype = Legemeldt
bransjer_alle<- bransjer_år %>% 
  select(-"sykefraværstyper") %>% 
  filter(kjønn == "Begge kjønn")

```

```{r tabell_1, warning = FALSE}
# tabell med tall - ti siste årene
suppressPackageStartupMessages(library(kableExtra))
tabell_bransjer_alle <- 
  bransjer_alle %>% 
  select(-c("2001":"2011"), - "kjønn") 

knitr::kable(tabell_bransjer_alle, caption = "Sykefravær totalt fordelt på næringer") 
```

```{r kvinner}
#bransjer, kvinner  - fraværstype = Legemeldt
bransjer_kvinner<- bransjer_år %>% 
  select(-"sykefraværstyper") %>% 
  filter(kjønn == "Kvinner")

```

```{r tabell_2, warning = FALSE}
# tabell med tall - ti siste årene

tabell_bransjer_kvinner <- 
  bransjer_kvinner %>% 
  select(-c("2001":"2011"), - "kjønn") 

knitr::kable(tabell_bransjer_kvinner, caption = "Sykefravær kvinner fordelt på næringer") 
```

```{r menn}
#bransjer, menn  - fraværstype = Legemeldt
bransjer_menn<- bransjer_år %>% 
  select(-"sykefraværstyper") %>% 
  filter(kjønn == "Menn")

```

```{r tabell_3, warning = FALSE}
# tabell med tall - ti siste årene

tabell_bransjer_menn <- 
  bransjer_menn %>% 
  select(-c("2001":"2011"), - "kjønn") 

knitr::kable(tabell_bransjer_menn, caption = "Sykefravær menn fordelt på næringer") 
```
